version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_user
      POSTGRES_DB: db
    volumes:
      - ./postgres:/postgres-init
    entrypoint: /postgres-init/init-script.sh
    networks:
      - app-network
    ports:
      - "5432:5432"

  tondeuse-app:
    image: openjdk:17
    volumes:
      - ./build/libs:/app
      - ./src/test/resources:/input-file
    working_dir: /app
    command: java -jar kata-tondeuse-0.0.1-SNAPSHOT.jar input.file=/input-file/testInput.txt
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge